### ISSUE TITLE
404: Chaning Text does not affect shown text

### ISSUE THREAD

**Issue by DJKnaeckebrot** [Assistants-Center/DBD-Soft-UI#100]
`error: {
        error404: {
            title: "Error 404",
            subtitle: "How'd you get here?",
            description:
                "It seems you have stumbled into the abyss. Click the button below to return to the dashboard",
        },`

![image](https://github.com/Discord-Dashboard/Soft-UI/assets/46864390/18f943e2-13f1-4781-ac3a-95d244c82d3f)

**Comment by mohaidarus** [comment]
Solved #101
